# Using 50 members of NumPy

In [46]:
import numpy as np
data = np.random.randn(3,3)
data

array([[ 0.42230086,  0.23198925,  0.20808688],
       [ 1.30515462,  1.05767155, -1.28995995],
       [ 0.37490215,  1.11943452,  0.04451903]])

In [47]:
data.shape

(3, 3)

In [48]:
data.dtype

dtype('float64')

In [49]:
array1 = np.array(data)
array1

array([[ 0.42230086,  0.23198925,  0.20808688],
       [ 1.30515462,  1.05767155, -1.28995995],
       [ 0.37490215,  1.11943452,  0.04451903]])

In [50]:
array2 = np.array([1,2,3,4,5,6])
array2

array([1, 2, 3, 4, 5, 6])

In [51]:
array3 = np.array([[1,2,3], [4,5,6,7]])
array3

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [52]:
data.ndim

2

In [53]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [54]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.empty((2,3,2))

array([[[1.15365577e-311, 2.86558075e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.55762979e-307, 3.69776220e-062]],

       [[7.11458528e-091, 1.27863103e+165],
        [5.41906099e-067, 3.60169552e+179],
        [6.48224659e+170, 5.82471487e+257]]])

In [56]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [59]:
np.asarray(array1)

array([[ 0.42230086,  0.23198925,  0.20808688],
       [ 1.30515462,  1.05767155, -1.28995995],
       [ 0.37490215,  1.11943452,  0.04451903]])

In [60]:
np.ones_like((1,2,3))

array([1, 1, 1])

In [61]:
np.zeros_like(np.zeros(2))

array([0., 0.])

In [62]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [63]:
np.identity(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])